apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
#images:
 # - name: argoproj/argocd
  #  newName: 
   # newTag: 
patches:
- path: argocd-configmap-patch.yaml
  target:
    kind: ConfigMap
    name: argocd-cm