# Customize according to your requirements
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-{{ .Values.spec.source.environment }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: resources/deployments/backend
    helm:
      # Use value file to provide service specific configuration for one environment
      valueFiles:
        - {{ .Values.spec.source.valueFile }}
      # Use parameters to set global variables which should be the same for all services in one env. (e.g. development)
      parameters:
        - name: "destination.namespace"
          value: {{ .Values.spec.destination.namespace }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m